version: 2

settings:
  libsodium: &LIBSODIUM libsodium-1.0.16
  version: &VERSION 1.0.16.1

workflows:
  version: 2
  build:
    jobs:
      - debian-stretch
      - alpine-3.6
      - macos-xcode-9.2
      - pack:
          requires:
            - debian-stretch
            - alpine-3.6
            - macos-xcode-9.2

common_steps:
  download: &DOWNLOAD
    name: Download libsodium
    environment:
      LIBSODIUM: *LIBSODIUM
    command: |
        curl -fsLo libsodium.tar.gz https://download.libsodium.org/libsodium/releases/$LIBSODIUM.tar.gz
        tar -xzf libsodium.tar.gz
  build: &BUILD
    name: Build libsodium
    working_directory: *LIBSODIUM
    command: |
        ./configure --disable-debug --prefix=/tmp/libsodium-build
        make
        make check
        make install
  finalize-so: &FINALIZE-SO
    name: Finalizing
    working_directory: *LIBSODIUM
    command: |
        mkdir -p ~/workspace/$CIRCLE_JOB/
        cp /tmp/libsodium-build/lib/libsodium.so ~/workspace/$CIRCLE_JOB/
        strip --strip-all ~/workspace/$CIRCLE_JOB/libsodium.so
  finalize-dylib: &FINALIZE-DYLIB
    name: Finalizing
    working_directory: *LIBSODIUM
    command: |
        mkdir -p ~/workspace/$CIRCLE_JOB/
        cp /tmp/libsodium-build/lib/libsodium.dylib ~/workspace/$CIRCLE_JOB/

jobs:
  pack:
    docker:
      - image: microsoft/dotnet:2.0-sdk
    steps:
      - run:
          name: Install Prerequisites
          command: |
              apt-get -qq update
              apt-get -qq install --yes --no-install-recommends python3 ca-certificates curl tar unzip make
      - attach_workspace:
          at: ~/workspace/
      - checkout
      - restore_cache:
          keys:
            - *LIBSODIUM
      - run:
          name: Preparing Makefile
          environment:
            VERSION: *VERSION
          command: python3 prepare.py $VERSION
      - run:
          name: Make NuGet Package
          command: make
      - save_cache:
          key: *LIBSODIUM
          paths:
            - cache
      - store_artifacts:
          path: artifacts
          destination: /

  debian-stretch:
    docker:
      - image: debian:stretch
    steps:
      - run:
          name: Install Prerequisites
          command: |
              apt-get -qq update
              apt-get -qq install --yes --no-install-recommends build-essential ca-certificates curl tar
      - run: *DOWNLOAD
      - run: *BUILD
      - run: *FINALIZE-SO
      - persist_to_workspace:
          root: ~/workspace/
          paths:
            - debian-stretch

  alpine-3.6:
    docker:
      - image: alpine:3.6
    steps:
      - run:
          name: Install Prerequisites
          command: |
              apk update
              apk add alpine-sdk ca-certificates curl tar
      - run: *DOWNLOAD
      - run: *BUILD
      - run: *FINALIZE-SO
      - persist_to_workspace:
          root: ~/workspace/
          paths:
            - alpine-3.6

  macos-xcode-9.2:
    macos:
      xcode: "9.2.0"
    steps:
      - run: *DOWNLOAD
      - run: *BUILD
      - run: *FINALIZE-DYLIB
      - persist_to_workspace:
          root: ~/workspace/
          paths:
            - macos-xcode-9.2
